# This is the main configuration file for Scissors.
# As you can see, there's tons to configure. Some options may impact gameplay, so use
# with caution, and make sure you know what each option does before configuring.
#
# If you need help with the configuration or have any questions related to Scissors,
# join us in our Discord.
#
# Discord: https://discord.com/invite/mtVQcHn58h
# Website: https://scissors.gg/ 
# Docs: https://javadoc.scissors.gg/1.20.1/ 

excludePlayersFromNbtComponents: false
componentDepthLimit: 128
chatSignaturesEnabled: false
commandSignsBypassPermissions: false
runCommandsInBooks: true
config-version: 5
