name: Server Updater
on:
  schedule:
  - cron: "0 18 * * MON,THU"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    if: github.repository == 'kaboomremake/server'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Fetch server jar
      run: scripts/fetch_server.sh

    - name: Fetch internal plugins
      run: scripts/fetch_internal_plugins.sh

    - name: Fetch external plugins
      run: scripts/fetch_external_plugins.sh

    - name: Update server and plugins
      run: |
        cp fetched_server/server.jar .
        cp fetched_plugins/*.jar plugins/

    - name: Push changes
      run: |
        git config --global user.name 'kaboombot'
        git config --global user.email '58372747+kaboombot@users.noreply.github.com'
        git commit -am "Update server and plugins"
        git push
